### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by ghost** [OdarGM/OdarBot#40]
internal/modules/cjs/loader.js:584
11:02 AM
    throw err;
11:02 AM
    ^
11:02 AM
11:02 AM
Error: Cannot find module 'm3u8stream/lib/parse-time'
11:02 AM
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
11:02 AM
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
11:02 AM
    at Module.require (internal/modules/cjs/loader.js:637:17)
11:02 AM
    at require (internal/modules/cjs/helpers.js:22:18)
11:02 AM
    at Object.<anonymous> (/rbd/pnpm-volume/f6cead61-ad20-4c21-a8d4-40dfa362d1f5/node_modules/.registry.npmjs.org/ytdl-core/0.29.7/node_modules/ytdl-core/lib/info-extras.js:5:21)
11:02 AM
    at Module._compile (internal/modules/cjs/loader.js:701:30)
11:02 AM
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
11:02 AM
    at Module.load (internal/modules/cjs/loader.js:600:32)
11:02 AM
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
11:02 AM
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by Pit896** [comment]
install module "parse-time"

**Comment by Justman10000** [comment]
`npm install parse-time`

**Comment by AdiRaihan46** [comment]
Check /app/package.json: command not found. Is a start script missing? https://glitch.com/help/failstart/
?
